### PR TITLE
acra: improvements

### PR DESCRIPTION
**Pull request by DF1E**
api key is private now - I will add it on releases

### CODE REVIEW

**Comment by balzathor** [comment]
Well instead of ACRA you can use Fabric.io. Acra has become sloppy now.

**Comment by DF1E** [comment]
Hi, I will try it because in my view Acra isn't comfortable, thanks for your idea!

**Comment by balzathor** [comment]
ACRA is pretty sloppy, Fabric has a good UI, and has the best crash analytics (Crashlytics) for free.

**Comment by DF1E** [comment]
done https://github.com/DF1E/SimpleExplorer/commit/e6106162b0f361ddefc96fd024571e645be2c2fb

**Comment by balzathor** [comment]
Yeah, all you need to do is install Fabric Plugin, it does the rest on its own. Seems good.
Now deploy a version and check Fabric dashboard

**Pull request merged**
