### PR TITLE
Feature #45 - file picking prototype

### PR DESCRIPTION
**Pull request by unrulygnu**
While not production-ready, the code is good enough (and runnable) from both commits to show approaches and get your feedback.

The first commit (7ad6bf7) uses the existing `BrowserActivity` and passes a `boolean` through to the `BrowserFragment`, using conditionals to modify views and behavior.  It has the lowest impact on the code base, but also results in code that is harder to maintain.

The second commit (d45b9c4) refactors most of `BrowserActivity` code to `AbstractBrowserActivity`, allowing `BrowserActivity` and the new `PickerActivity` to extend it and share behavior.  This approach has a bigger impact on the existing code base, but it results in much easier code maintenance in the future, as well as extensibility.  This is the approach I prefer, even though it's more work for me to prepare for production. :)

@DF1E , could you take a quick look at the diffs and let me know what you think, if you'd prefer some changes, etc?  Many thanks!

### CODE REVIEW

**Comment by DF1E** [comment]
At first glance it looks great! I will test the current changes when I have some time, thanks!

**Comment by unrulygnu** [comment]
I'm probably going to push another 3 or 4 commits to this branch before it's production-ready.  If you want, I can squash them before the final commit.

**Comment by DF1E** [comment]
Yes, it would be nice if all the commits were summarized in a final commit

**Comment by DF1E** [comment]
I created a new pull request to the dev branch

**Pull request closed without merging**
